In [1]:
import numpy as np

# Q1

In [6]:
arr = np.arange(1, 11)
print("Sum: ", arr.sum())
print("Mean:", arr.mean())
print("Product: ", arr.prod())

Sum:  55
Mean: 5.5
Product:  3628800


# Q2

In [12]:
arr = np.random.randint(10, size=(3, 3))
arr.transpose()

array([[4, 5, 4],
       [0, 9, 7],
       [1, 1, 0]], dtype=int32)

# Q3

In [15]:
arr = np.arange(20)
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Q4

In [20]:
arr1 = np.arange(25)
arr1 = arr1.reshape(5,5)
arr2 = np.arange(26, 51)
arr2 = arr2.reshape(5,5)
print("Addition:\n", arr1 + arr2)
print("Subtraction:\n", arr1 - arr2)
print("Multiplication:\n", arr1 * arr2)
print("Division:\n", arr1 / arr2)


Addition:
 [[26 28 30 32 34]
 [36 38 40 42 44]
 [46 48 50 52 54]
 [56 58 60 62 64]
 [66 68 70 72 74]]
Subtraction:
 [[-26 -26 -26 -26 -26]
 [-26 -26 -26 -26 -26]
 [-26 -26 -26 -26 -26]
 [-26 -26 -26 -26 -26]
 [-26 -26 -26 -26 -26]]
Multiplication:
 [[   0   27   56   87  120]
 [ 155  192  231  272  315]
 [ 360  407  456  507  560]
 [ 615  672  731  792  855]
 [ 920  987 1056 1127 1200]]
Division:
 [[0.         0.03703704 0.07142857 0.10344828 0.13333333]
 [0.16129032 0.1875     0.21212121 0.23529412 0.25714286]
 [0.27777778 0.2972973  0.31578947 0.33333333 0.35      ]
 [0.36585366 0.38095238 0.39534884 0.40909091 0.42222222]
 [0.43478261 0.44680851 0.45833333 0.46938776 0.48      ]]


# Q5

In [21]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

# Q6

In [25]:
arr = np.arange(4).reshape(2, 2)
np.linalg.det(arr)

np.float64(-2.0)

# Q7

In [26]:
arr = np.random.randn(50)
print("Max Index: ", np.argmax(arr))
print("Min Index: ", np.argmin(arr))

Max Index:  41
Min Index:  17


# Q8

In [35]:
# Ax = B
A = np.array([
    [2, 3, -1],
    [4, 1, 2],
    [-2, 5, 3]
])

B = np.array([5, 6, -4])
np.linalg.solve(A, B)

array([ 1.75      ,  0.28571429, -0.64285714])

# Q9

In [36]:
arr = np.arange(25)
np.percentile(arr, 75)

np.float64(18.0)

# Q10

In [39]:
def normalize_array(arr):
    mean = np.mean(arr)
    std_dev = np.std(arr)

    return (arr - mean) / std_dev

arr = np.random.randint(1, 20, size=10)
normalize_array(arr)

array([-1.67604128, -1.84533837,  0.35552391,  0.18622681,  0.18622681,
        0.8634152 ,  1.0327123 ,  0.52482101, -0.66025868,  1.0327123 ])